#!/bin/sh

clean=0
update=0
rebuild=1

for arg in $@; do
    case "$arg" in
    clean)
        clean=1
        ;;
    update)
        update=1
        ;;
    rebuild)
        rebuild=1
        ;;
    esac
done

[ "$clean" -gt 0 ] && ./scripts/clean
[ "$update" -gt 0 ] && ./scripts/update
[ "$rebuild" -gt 0 ] && ./scripts/rebuild-local
