# https://docs.noctalia.dev/noctalia/configuration/shell/

[shell]
offline_mode = true
telemetry_enabled = false

font_family = "GoMono Nerd Font"
time_format = "{:%-I:%M %p}"
setup_wizard_enabled = false
avatar_path = "~/.face"

[shell.launcher]
app_grid = true
sort_by_usage = false

[shell.screenshot]
save_to_file = true
directory = "~/Pictures/Screenshots"
confirm_region = true
show_cursor = true
annotate = true

# https://docs.noctalia.dev/noctalia/bar/

[bar]
order = ["default"]

[bar.default]
enabled = true
auto_hide = true
smart_auto_hide = true
reserve_space = false
position = "bottom"
radius_bottom_left = 0
radius_bottom_right = 0
show_on_workspace_switch = false
layer = "overlay"

thickness = 64
background_opacity = 1.0
border_width = 2
contact_shadow = true
concave_edge_corners = false
margin_ends = 512
margin_edge = -2
padding = 12
widget_spacing = 8

capsule = true
capsule_thickness = 0.5
capsule_radius = 2.0
capsule_opacity = 1.0

start = ["session", "clock", "network", "bluetooth"]
center = ["workspaces"]
end = ["tray", "volume", "brightness", "battery", "clipboard", "notifications"]

# https://docs.noctalia.dev/noctalia/desktop/wallpaper/

[wallpaper]
enabled = true
fill_color = "#191724"
directory = "~/Pictures/Wallpapers"

[wallpaper.default]
path = "~/Pictures/Wallpapers/seaside-bus-stop-view.png"

# https://docs.noctalia.dev/noctalia/services/battery/

[battery]
warning_threshold = 50

[brightness]
minimum_brightness = 0.1

[idle]
behavior_order = ["lock", "screen-off", "suspend"]
pre_action_fade_seconds = 2.0
[idle.behavior.lock]
enabled = true
timeout = 600
action = "lock"
[idle.behavior.screen-off]
enabled = false
[idle.behavior.suspend]
enabled = true
timeout = 900
action = "lock_and_suspend"

[system.monitor]
enabled = false

[weather]
enabled = false
